service: juddbaguio-github

provider:
  name: aws
  memorySize: 128
  region: ap-southeast-1
  runtime: provided.al2
  stackName: juddbaguio-github
    
package: 
  individually: true

functions:
  juddbaguio:
    layers:
      - arn:aws:lambda:ap-southeast-1:753240598075:layer:LambdaAdapterLayerX86:11
    package: 
      artifact: target/lambda/serverless-redirect/bootstrap.zip
    handler: bootstrap
    events:
      - http:
          method: GET
          path: /
          cors: true